server:
  port: 8080

spring:
  application:
    name: thrombosis-backend
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      id-type: auto
